# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rbac.group', verbose_name='所在分组'),
        ),
    ]
