# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20171108_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(default='list', max_length=32, verbose_name='代码'),
        ),
    ]
