# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='teacher_to_cls',
            field=models.ManyToManyField(to='app01.ClassList'),
        ),
    ]
