# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171103_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='aa@qq.com', max_length=254),
        ),
    ]
