# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171104_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[(1, '男'), (2, '女')], max_length=10),
        ),
    ]
