# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20171104_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name_plural': '班级表'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '学生表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name_plural': '用户类型表'},
        ),
        migrations.AlterField(
            model_name='classlist',
            name='caption',
            field=models.CharField(max_length=32, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='headmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name='所在班级'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='teacher_to_cls',
            field=models.ManyToManyField(to='app01.ClassList', verbose_name='老师所交班级'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserType', verbose_name='用户类型'),
        ),
    ]
