# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBook', '0002_auto_20171027_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
