# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='组名称')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(default='list', max_length=32, verbose_name='代码'),
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rbac.Group', verbose_name='s所在权限组'),
        ),
    ]
