# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
