# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171117_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网站文章分类名称')),
            ],
            options={
                'verbose_name_plural': '网站文章分类表',
            },
        ),
        migrations.CreateModel(
            name='SiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网站分类名称')),
            ],
            options={
                'verbose_name_plural': '网站分类表',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='article2tag',
            options={'verbose_name_plural': '文章和标签关联表'},
        ),
        migrations.AlterModelOptions(
            name='articledetail',
            options={'verbose_name_plural': '文章详细表'},
        ),
        migrations.AlterModelOptions(
            name='articleup',
            options={'verbose_name_plural': '文章点赞表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'category', 'verbose_name_plural': '文章分类表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='commentup',
            options={'verbose_name_plural': '评论点赞表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签表'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_type_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='差评数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='articleup',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Article', verbose_name='点赞的文章'),
        ),
        migrations.AlterField(
            model_name='articleup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='文章点赞id'),
        ),
        migrations.AlterField(
            model_name='articleup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Userinfo', verbose_name='点赞人'),
        ),
        migrations.AlterField(
            model_name='commentup',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Comment', verbose_name='点赞的评论'),
        ),
        migrations.AlterField(
            model_name='commentup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='评论点赞id'),
        ),
        migrations.AlterField(
            model_name='commentup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Userinfo', verbose_name='点赞人'),
        ),
        migrations.AddField(
            model_name='sitearticlecategory',
            name='siteCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.SiteCategory', verbose_name='所属网站分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='siteArticleCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.SiteArticleCategory', verbose_name='所属网站文章分类'),
        ),
    ]
