# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20171121_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDown',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章反对id')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Article', verbose_name='反对的文章')),
            ],
            options={
                'verbose_name_plural': '文章反对表',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '博客表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AddField(
            model_name='articledown',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Userinfo', verbose_name='反对人'),
        ),
    ]
