# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20171125_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='registTime',
            field=models.DateTimeField(verbose_name='注册时间'),
        ),
    ]
