# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20171129_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='registTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
