# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Headmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('sal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10)),
                ('email', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10)),
                ('email', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Class')),
                ('headmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Headmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('sal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10)),
                ('email', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(to='app01.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='headmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Headmaster'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(to='app01.Teacher'),
        ),
    ]
